# ML Lab07-1 : Learning rate, Evaluation

## Training and Test datasets

In [1]:
import tensorflow as tf

x_data = [[1, 2, 1], [1, 3, 2], [1, 3, 4], [1, 5, 5],
          [1, 7, 5], [1, 2, 5], [1, 6, 6], [1, 7, 7]]
y_data = [[0, 0, 1], [0, 0, 1], [0, 0, 1], [0, 1, 0],
          [0, 1, 0], [0, 1, 0], [1, 0, 0], [1, 0, 0]]

# Evaluation our model using this test dataset
x_test = [[2, 1, 1], [3, 1, 2], [3, 3, 4]]
y_test = [[0, 0, 1], [0, 0, 1], [0, 0, 1]]

X = tf.placeholder("float", [None, 3])
Y = tf.placeholder("float", [None, 3])
W = tf.Variable(tf.random_normal([3,3]))
b = tf.Variable(tf.random_normal([3]))

# tf.nn.softmax compute softmax activations
# softmax = exp(Logistic) / reduce_sum(exp(Logits), dim)
hypothesis = tf.nn.softmax(tf.matmul(X, W) + b)

# Cross entropy cost/Loss
cost = tf.reduce_mean(-tf.reduce_sum(Y * tf.log(hypothesis), axis=1))
optimizer = tf.train.GradientDescentOptimizer(learning_rate=0.1).minimize(cost)


# ------------ 위의 소스 코드까지가 graph ----------------------

prediction = tf.arg_max(hypothesis, 1)
is_correct = tf.equal(prediction, tf.arg_max(Y, 1))
accuracy = tf.reduce_mean(tf.cast(is_correct, tf.float32))

# Launch graph
with tf.Session() as sess:
    #initailize
    sess.run(tf.global_variables_initializer())
    
    for step in range(201):
        cost_val, W_val, _ = sess.run([cost, W, optimizer],
                                     feed_dict={X: x_data, Y: y_data})
        if step % 20 == 0:
            print step, cost_val, W_val 

    # predict
    print "Prediction:", sess.run(prediction, feed_dict={X: x_test})
    # Calculate the accuracy
    print "Accuracy: ", sess.run(accuracy, feed_dict={X: x_test, Y: y_test})


Instructions for updating:
Use `argmax` instead
0 7.837591 [[ 1.1419189  -0.49156463  1.439095  ]
 [-0.7672531   0.17333063 -1.0920527 ]
 [-1.0635648   1.2491653   1.8695364 ]]
20 1.0615451 [[ 1.1210476  -0.55201083  1.5204127 ]
 [ 0.05190028 -0.54985064 -1.1880246 ]
 [ 0.16761729  0.95104367  0.93647623]]
40 0.86181664 [[ 0.9376013  -0.5342438   1.6860919 ]
 [-0.12559101 -0.61840737 -0.9419768 ]
 [ 0.4238496   1.0008209   0.6304668 ]]
60 0.7695284 [[ 0.7921984  -0.5243351   1.8215863 ]
 [-0.24149196 -0.6344022  -0.8100809 ]
 [ 0.60226506  1.0105876   0.4422847 ]]
80 0.7189379 [[ 0.66637707 -0.5151936   1.9382663 ]
 [-0.31224304 -0.63285124 -0.7408808 ]
 [ 0.72573704  1.0073546   0.3220456 ]]
100 0.6856191 [[ 0.55196553 -0.5049175   2.0424016 ]
 [-0.35341468 -0.62749135 -0.70506895]
 [ 0.8136185   1.0012883   0.2402307 ]]
120 0.66049093 [[ 0.44553772 -0.49341014  2.1373224 ]
 [-0.3765802  -0.6219276  -0.6874671 ]
 [ 0.8794393   0.99491894  0.18077931]]
140 0.63990474 [[ 0.34542066 -0.4

### Big learning rate

In [2]:
import tensorflow as tf

x_data = [[1, 2, 1], [1, 3, 2], [1, 3, 4], [1, 5, 5],
          [1, 7, 5], [1, 2, 5], [1, 6, 6], [1, 7, 7]]
y_data = [[0, 0, 1], [0, 0, 1], [0, 0, 1], [0, 1, 0],
          [0, 1, 0], [0, 1, 0], [1, 0, 0], [1, 0, 0]]

# Evaluation our model using this test dataset
x_test = [[2, 1, 1], [3, 1, 2], [3, 3, 4]]
y_test = [[0, 0, 1], [0, 0, 1], [0, 0, 1]]

X = tf.placeholder("float", [None, 3])
Y = tf.placeholder("float", [None, 3])
W = tf.Variable(tf.random_normal([3,3]))
b = tf.Variable(tf.random_normal([3]))

# tf.nn.softmax compute softmax activations
# softmax = exp(Logistic) / reduce_sum(exp(Logits), dim)
hypothesis = tf.nn.softmax(tf.matmul(X, W) + b)

# Cross entropy cost/Loss
cost = tf.reduce_mean(-tf.reduce_sum(Y * tf.log(hypothesis), axis=1))
optimizer = tf.train.GradientDescentOptimizer(learning_rate=1.5).minimize(cost)


# ------------ 위의 소스 코드까지가 graph ----------------------

prediction = tf.arg_max(hypothesis, 1)
is_correct = tf.equal(prediction, tf.arg_max(Y, 1))
accuracy = tf.reduce_mean(tf.cast(is_correct, tf.float32))

# Launch graph
with tf.Session() as sess:
    #initailize
    sess.run(tf.global_variables_initializer())
    
    for step in range(201):
        cost_val, W_val, _ = sess.run([cost, W, optimizer],
                                     feed_dict={X: x_data, Y: y_data})
        if step % 20 == 0:
            print step, cost_val, W_val 

    # predict
    print "Prediction:", sess.run(prediction, feed_dict={X: x_test})
    # Calculate the accuracy
    print "Accuracy: ", sess.run(accuracy, feed_dict={X: x_test, Y: y_test})


0 8.203156 [[ 0.42684644 -1.4663756  -0.08077377]
 [ 2.193118   -1.856834    3.1821587 ]
 [ 0.69007254 -2.310068    0.9290008 ]]
20 nan [[nan nan nan]
 [nan nan nan]
 [nan nan nan]]
40 nan [[nan nan nan]
 [nan nan nan]
 [nan nan nan]]
60 nan [[nan nan nan]
 [nan nan nan]
 [nan nan nan]]
80 nan [[nan nan nan]
 [nan nan nan]
 [nan nan nan]]
100 nan [[nan nan nan]
 [nan nan nan]
 [nan nan nan]]
120 nan [[nan nan nan]
 [nan nan nan]
 [nan nan nan]]
140 nan [[nan nan nan]
 [nan nan nan]
 [nan nan nan]]
160 nan [[nan nan nan]
 [nan nan nan]
 [nan nan nan]]
180 nan [[nan nan nan]
 [nan nan nan]
 [nan nan nan]]
200 nan [[nan nan nan]
 [nan nan nan]
 [nan nan nan]]
Prediction: [0 0 0]
Accuracy:  0.0


### Small learning rate

In [3]:
import tensorflow as tf

x_data = [[1, 2, 1], [1, 3, 2], [1, 3, 4], [1, 5, 5],
          [1, 7, 5], [1, 2, 5], [1, 6, 6], [1, 7, 7]]
y_data = [[0, 0, 1], [0, 0, 1], [0, 0, 1], [0, 1, 0],
          [0, 1, 0], [0, 1, 0], [1, 0, 0], [1, 0, 0]]

# Evaluation our model using this test dataset
x_test = [[2, 1, 1], [3, 1, 2], [3, 3, 4]]
y_test = [[0, 0, 1], [0, 0, 1], [0, 0, 1]]

X = tf.placeholder("float", [None, 3])
Y = tf.placeholder("float", [None, 3])
W = tf.Variable(tf.random_normal([3,3]))
b = tf.Variable(tf.random_normal([3]))

# tf.nn.softmax compute softmax activations
# softmax = exp(Logistic) / reduce_sum(exp(Logits), dim)
hypothesis = tf.nn.softmax(tf.matmul(X, W) + b)

# Cross entropy cost/Loss
cost = tf.reduce_mean(-tf.reduce_sum(Y * tf.log(hypothesis), axis=1))
optimizer = tf.train.GradientDescentOptimizer(learning_rate=1e-10).minimize(cost)


# ------------ 위의 소스 코드까지가 graph ----------------------

prediction = tf.arg_max(hypothesis, 1)
is_correct = tf.equal(prediction, tf.arg_max(Y, 1))
accuracy = tf.reduce_mean(tf.cast(is_correct, tf.float32))

# Launch graph
with tf.Session() as sess:
    #initailize
    sess.run(tf.global_variables_initializer())
    
    for step in range(201):
        cost_val, W_val, _ = sess.run([cost, W, optimizer],
                                     feed_dict={X: x_data, Y: y_data})
        if step % 20 == 0:
            print step, cost_val, W_val 

    # predict
    print "Prediction:", sess.run(prediction, feed_dict={X: x_test})
    # Calculate the accuracy
    print "Accuracy: ", sess.run(accuracy, feed_dict={X: x_test, Y: y_test})


0 2.2304935 [[ 0.4426145   1.4135212  -0.46055332]
 [-0.39649576  0.50344855 -1.4779618 ]
 [-0.636693   -1.8015283  -0.40372345]]
20 2.2304935 [[ 0.4426145   1.4135212  -0.46055332]
 [-0.39649576  0.50344855 -1.4779618 ]
 [-0.636693   -1.8015283  -0.40372345]]
40 2.2304935 [[ 0.4426145   1.4135212  -0.46055332]
 [-0.39649576  0.50344855 -1.4779618 ]
 [-0.636693   -1.8015283  -0.40372345]]
60 2.2304935 [[ 0.4426145   1.4135212  -0.46055332]
 [-0.39649576  0.50344855 -1.4779618 ]
 [-0.636693   -1.8015283  -0.40372345]]
80 2.2304935 [[ 0.4426145   1.4135212  -0.46055332]
 [-0.39649576  0.50344855 -1.4779618 ]
 [-0.636693   -1.8015283  -0.40372345]]
100 2.2304935 [[ 0.4426145   1.4135212  -0.46055332]
 [-0.39649576  0.50344855 -1.4779618 ]
 [-0.636693   -1.8015283  -0.40372345]]
120 2.2304935 [[ 0.4426145   1.4135212  -0.46055332]
 [-0.39649576  0.50344855 -1.4779618 ]
 [-0.636693   -1.8015283  -0.40372345]]
140 2.2304935 [[ 0.4426145   1.4135212  -0.46055332]
 [-0.39649576  0.50344855 -1.

## Non-normalized inputs

```
xy = np.array([[828.659973, 833.450012, 908100, 828.349976, 831.659973],
               [823.02002, 828.070007, 1828100, 821.655029, 828.070007],
               [819.929993, 824.400024, 1438100, 818.97998, 824.159973],
               [816, 820.958984, 1008100, 815.48999, 819.23999],
               [819.359985, 823, 1188100, 818.469971, 818.97998],
               [819, 823, 1198100, 816, 820.450012],
               [811.700012, 815.25, 1098100, 809.780029, 813.669983],
               [809.51001, 816.659973, 1398100, 804.539978, 809.559998]])
```

In [4]:
import tensorflow as tf
import numpy as np

xy = np.array([[828.659973, 833.450012, 908100, 828.349976, 831.659973],
               [823.02002, 828.070007, 1828100, 821.655029, 828.070007],
               [819.929993, 824.400024, 1438100, 818.97998, 824.159973],
               [816, 820.958984, 1008100, 815.48999, 819.23999],
               [819.359985, 823, 1188100, 818.469971, 818.97998],
               [819, 823, 1198100, 816, 820.450012],
               [811.700012, 815.25, 1098100, 809.780029, 813.669983],
               [809.51001, 816.659973, 1398100, 804.539978, 809.559998]])

x_data = xy[:, 0:-1]
y_data = xy[:, [-1]]

# Evaluation our model using this test dataset

X = tf.placeholder(tf.float32, [None, 4])
Y = tf.placeholder(tf.float32, [None, 1])
W = tf.Variable(tf.random_normal([4,1]), name='weight')
b = tf.Variable(tf.random_normal([1]), name='bias')


hypothesis = tf.matmul(X, W) + b
cost = tf.reduce_mean(tf.square(hypothesis - Y))

# Cross entropy cost/Loss
optimizer = tf.train.GradientDescentOptimizer(learning_rate=1e-5)
train = optimizer.minimize(cost)

# ------------ 위의 소스 코드까지가 graph ----------------------

# Launch graph
with tf.Session() as sess:
    #initailize
    sess.run(tf.global_variables_initializer())
    
    for step in range(11):
        cost_val, hy_val, _ = sess.run([cost, hypothesis, train],
                                     feed_dict={X: x_data, Y: y_data})
        print step, "Cost: ", cost_val, "\nPrediction:\n", hy_val 

0 Cost:  598648800000.0 
Prediction:
[[ -545071.75]
 [-1097737.5 ]
 [ -863458.25]
 [ -605150.56]
 [ -713278.75]
 [ -719287.6 ]
 [ -659218.8 ]
 [ -839437.8 ]]
1 Cost:  6.5772375e+26 
Prediction:
[[1.8090604e+13]
 [3.6418240e+13]
 [2.8648917e+13]
 [2.0082739e+13]
 [2.3668581e+13]
 [2.3867794e+13]
 [2.1875659e+13]
 [2.7852062e+13]]
2 Cost:  inf 
Prediction:
[[-5.9963747e+20]
 [-1.2071316e+21]
 [-9.4960699e+20]
 [-6.6566946e+20]
 [-7.8452706e+20]
 [-7.9113025e+20]
 [-7.2509826e+20]
 [-9.2319415e+20]]
3 Cost:  inf 
Prediction:
[[1.9875796e+28]
 [4.0012011e+28]
 [3.1476008e+28]
 [2.2064514e+28]
 [2.6004209e+28]
 [2.6223081e+28]
 [2.4034361e+28]
 [3.0600519e+28]]
4 Cost:  inf 
Prediction:
[[-6.5881006e+35]
 [-1.3262522e+36]
 [-1.0433148e+36]
 [-7.3135810e+35]
 [-8.6194465e+35]
 [-8.6919942e+35]
 [-7.9665138e+35]
 [-1.0142956e+36]]
5 Cost:  inf 
Prediction:
[[inf]
 [inf]
 [inf]
 [inf]
 [inf]
 [inf]
 [inf]
 [inf]]
6 Cost:  nan 
Prediction:
[[nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]

### Normalized inputs (min-max scale

```
xy = MinMaxScaler(xy)
```


In [5]:
import tensorflow as tf
import numpy as np

def MinMaxScaler(data):

    numerator = data - np.min(data, 0)

    denominator = np.max(data, 0) - np.min(data, 0)

    # noise term prevents the zero division

    return numerator / (denominator + 1e-7)

xy = np.array([[828.659973, 833.450012, 908100, 828.349976, 831.659973],
               [823.02002, 828.070007, 1828100, 821.655029, 828.070007],
               [819.929993, 824.400024, 1438100, 818.97998, 824.159973],
               [816, 820.958984, 1008100, 815.48999, 819.23999],
               [819.359985, 823, 1188100, 818.469971, 818.97998],
               [819, 823, 1198100, 816, 820.450012],
               [811.700012, 815.25, 1098100, 809.780029, 813.669983],
               [809.51001, 816.659973, 1398100, 804.539978, 809.559998]])

xy = MinMaxScaler(xy)

print xy




[[0.99999999 0.99999999 0.         1.         1.        ]
 [0.70548491 0.70439552 1.         0.71881782 0.83755791]
 [0.54412549 0.50274824 0.57608696 0.606468   0.6606331 ]
 [0.33890353 0.31368023 0.10869565 0.45989134 0.43800918]
 [0.51436    0.42582389 0.30434783 0.58504805 0.42624401]
 [0.49556179 0.42582389 0.31521739 0.48131134 0.49276137]
 [0.11436064 0.         0.20652174 0.22007776 0.18597238]
 [0.         0.07747099 0.5326087  0.         0.        ]]


In [6]:
import tensorflow as tf
import numpy as np

def MinMaxScaler(data):

    numerator = data - np.min(data, 0)

    denominator = np.max(data, 0) - np.min(data, 0)

    # noise term prevents the zero division

    return numerator / (denominator + 1e-7)

xy = np.array([[828.659973, 833.450012, 908100, 828.349976, 831.659973],
               [823.02002, 828.070007, 1828100, 821.655029, 828.070007],
               [819.929993, 824.400024, 1438100, 818.97998, 824.159973],
               [816, 820.958984, 1008100, 815.48999, 819.23999],
               [819.359985, 823, 1188100, 818.469971, 818.97998],
               [819, 823, 1198100, 816, 820.450012],
               [811.700012, 815.25, 1098100, 809.780029, 813.669983],
               [809.51001, 816.659973, 1398100, 804.539978, 809.559998]])

xy = MinMaxScaler(xy)

x_data = xy[:, 0:-1]
y_data = xy[:, [-1]]

# Evaluation our model using this test dataset

X = tf.placeholder(tf.float32, [None, 4])
Y = tf.placeholder(tf.float32, [None, 1])
W = tf.Variable(tf.random_normal([4,1]), name='weight')
b = tf.Variable(tf.random_normal([1]), name='bias')


hypothesis = tf.matmul(X, W) + b
cost = tf.reduce_mean(tf.square(hypothesis - Y))

# Cross entropy cost/Loss
optimizer = tf.train.GradientDescentOptimizer(learning_rate=1e-5)
train = optimizer.minimize(cost)

# ------------ 위의 소스 코드까지가 graph ----------------------

# Launch graph
with tf.Session() as sess:
    #initailize
    sess.run(tf.global_variables_initializer())
    
    for step in range(2001):
        cost_val, hy_val, _ = sess.run([cost, hypothesis, train],
                                     feed_dict={X: x_data, Y: y_data})
        if step % 1000 == 0:
            print step, "Cost: ", cost_val, "\nPrediction:\n", hy_val 

0 Cost:  0.010124576 
Prediction:
[[1.1515926 ]
 [0.8121542 ]
 [0.60433173]
 [0.36825824]
 [0.55450696]
 [0.5970996 ]
 [0.10448615]
 [0.12392762]]
1000 Cost:  0.010014865 
Prediction:
[[1.1495475 ]
 [0.81037384]
 [0.6028282 ]
 [0.36706638]
 [0.5530996 ]
 [0.59574294]
 [0.10363788]
 [0.12314511]]
2000 Cost:  0.009911973 
Prediction:
[[1.14755   ]
 [0.8086455 ]
 [0.60136795]
 [0.36590913]
 [0.55173117]
 [0.5944254 ]
 [0.10281877]
 [0.12239674]]
