# ML Lab06-1 : TensorFlow로 Softmax Classification 구현

## Softmax function

```python
XW = Y -> tf.matmul(X,W)+b

hypothesis = tf.nn.softmax(tf.matmul(X,W)+b)

```

## Cost function: cross entropy

$$ L = {1 \over N}\sum_{i} D(WX_i + b), L_i) $$
<br>
```python
#cross entropy cost/Loss
cost = tf.reduce.mean(-tf.reduce_sum(Y * tf.log(hypothesis), axis=1))
optimizer = tf.train.GradientDescentOptimizer(learning_rate=0.1).minimize(cost)
```


In [12]:
import tensorflow as tf

# multi variable data
x_data = [[1, 2, 1, 1], [2, 1, 3, 2], [3, 1, 3, 4], [4, 1, 5, 5], [1, 7, 5, 5], [1, 2, 5, 6], [1, 6, 6, 6], [1, 7, 7, 7]]
y_data = [[0, 0, 1], [0, 0, 1], [0, 0, 1], [0, 1, 0], [0, 1, 0], [0, 1, 0], [1, 0, 0], [1, 0, 0]]

# placeholder를 만들때는 shape에 꼭 주의 해야한다!
X = tf.placeholder(tf.float32, shape=[None, 4])
Y = tf.placeholder(tf.float32, shape=[None, 3])
nb_classes = 3

W = tf.Variable(tf.random_normal([4, nb_classes]), name='weight')
b = tf.Variable(tf.random_normal([nb_classes]), name='bias')

# tf.nn.softmax compute softmax activations
# softmax = exp(Logistic) / reduce_sum(exp(Logits), dim)
hypothesis = tf.nn.softmax(tf.matmul(X, W) + b)


# Cross entropy cost/Loss
cost = tf.reduce_mean(-tf.reduce_sum(Y * tf.log(hypothesis), axis=1))
optimizer = tf.train.GradientDescentOptimizer(learning_rate=0.1).minimize(cost)


# ------------ 위의 소스 코드까지가 graph ----------------------

# Launch graph
with tf.Session() as sess:
    #initailize
    sess.run(tf.global_variables_initializer())
    
    for step in range(2001):
        sess.run(optimizer, feed_dict={X: x_data, Y: y_data})
        if step % 200 == 0:
            print step, sess.run(cost, feed_dict={X: x_data, Y: y_data})
    
    #Test & one-hot encoding
    a = sess.run(hypothesis, feed_dict={X: [[1, 11, 7, 9]]})
    print a, sess.run(tf.arg_max(a, 1))
    
    all = sess.run(hypothesis, feed_dict={X: [[1, 11, 7, 9],
                                             [1, 3, 4, 3],
                                             [1, 1, 0, 1]]})
    print all, sess.run(tf.arg_max(all, 1))
            

0 1.838775
200 0.6086009
400 0.5047752
600 0.40911883
800 0.31603417
1000 0.24591187
1200 0.22185314
1400 0.20204955
1600 0.18536782
1800 0.17113404
2000 0.15885572
[[3.9356574e-03 9.9606043e-01 3.8644030e-06]] [1]
[[3.9356574e-03 9.9606043e-01 3.8644030e-06]
 [8.8794374e-01 1.0978861e-01 2.2676068e-03]
 [1.0757113e-08 2.5400039e-04 9.9974602e-01]] [1 0 2]
