# ML Lab04-2 : Loading Data from File

## Loading data from file

Data가 많아지면서 소스코드에 data를 올리기엔 부담이 생긴다.  
그래서 Data를 load 해오는데 이 때 csv 파일을 주로 이용한다.  
<br>
가장 간단하게 load해오는 방법은 numpy에 loadtxt를 이용한다.

In [1]:
import tensorflow as tf
import numpy as np

# loadtxt 이용하기 단점은 전체의 data가 같은 data type이어야한다.
xy = np.loadtxt('data-01-test-score.csv', delimiter=',', dtype=np.float32)

# x와 y를 나누어야하는데 이 때 python의 기능 중 slice가 필요하다.
# python Slicing 공부하기
# numpy에서는 더욱 막강한 slicing이 가능해진다! 찾아서 공부하기

#: 전체 행을 다 가져온다, 0:-1 마지막꺼 전까지 가져오겠다.
x_data = xy[:, 0:-1]
#: 전체 행을 가져오는데 마지막 행만 가져오겠다.
y_data = xy[:, [-1]]

print x_data.shape, x_data, len(x_data)
print y_data.shape, y_data


(25, 3) [[ 73.  80.  75.]
 [ 93.  88.  93.]
 [ 89.  91.  90.]
 [ 96.  98. 100.]
 [ 73.  66.  70.]
 [ 53.  46.  55.]
 [ 69.  74.  77.]
 [ 47.  56.  60.]
 [ 87.  79.  90.]
 [ 79.  70.  88.]
 [ 69.  70.  73.]
 [ 70.  65.  74.]
 [ 93.  95.  91.]
 [ 79.  80.  73.]
 [ 70.  73.  78.]
 [ 93.  89.  96.]
 [ 78.  75.  68.]
 [ 81.  90.  93.]
 [ 88.  92.  86.]
 [ 78.  83.  77.]
 [ 82.  86.  90.]
 [ 86.  82.  89.]
 [ 78.  83.  85.]
 [ 76.  83.  71.]
 [ 96.  93.  95.]] 25
(25, 1) [[152.]
 [185.]
 [180.]
 [196.]
 [142.]
 [101.]
 [149.]
 [115.]
 [175.]
 [164.]
 [141.]
 [141.]
 [184.]
 [152.]
 [148.]
 [192.]
 [147.]
 [183.]
 [177.]
 [159.]
 [177.]
 [175.]
 [175.]
 [149.]
 [192.]]


In [2]:
import tensorflow as tf
import numpy as np

# loadtxt 이용하기 단점은 전체의 data가 같은 data type이어야한다.
xy = np.loadtxt('data-01-test-score.csv', delimiter=',', dtype=np.float32)

# x와 y를 나누어야하는데 이 때 python의 기능 중 slice가 필요하다.
# python Slicing 공부하기
# numpy에서는 더욱 막강한 slicing이 가능해진다! 찾아서 공부하기

#: 전체 행을 다 가져온다, 0:-1 마지막꺼 전까지 가져오겠다.
x_data = xy[:, 0:-1]
#: 전체 행을 가져오는데 마지막 행만 가져오겠다.
y_data = xy[:, [-1]]

X = tf.placeholder(tf.float32, shape=[None, 3])
Y = tf.placeholder(tf.float32, shape=[None, 1])

W = tf.Variable(tf.random_normal([3, 1]), name='weight')
b = tf.Variable(tf.random_normal([1]), name='bias')

# hypothesis
hypothesis = tf.matmul(X, W) + b

# cost/Los function
# 이 전에 쓰던 것과 동일함
cost = tf.reduce_mean(tf.square(hypothesis - Y))

#Minimize learning_rate를 낮게 줌
optimizer = tf.train.GradientDescentOptimizer(learning_rate=1e-5)
train = optimizer.minimize(cost)


sess = tf.Session()
sess.run(tf.global_variables_initializer())

for step in range(2001):
    #train을 돌리고 그 때, cost와 hypothes를 같이 기록을 해서 출력을 하는 모델
    cost_val, hy_val, _ = sess.run([cost, hypothesis, train],
                                  feed_dict={X: x_data, Y: y_data})
    if step % 100 == 0:
        print step ,'Cost : ', cost_val,"\n Prediction: \n", hy_val,"\n"
              

# Ask my score
print "Your score will be ", sess.run(hypothesis,
                                    feed_dict={X: [[100, 70, 101]]})
print "Other score will be ", sess.run(hypothesis,
                                      feed_dict={X: [[60, 80, 110], [90, 100, 80]]})

0 Cost :  1111.3954 
 Prediction: 
[[119.41473 ]
 [147.72069 ]
 [143.19298 ]
 [158.96211 ]
 [111.104576]
 [ 86.83268 ]
 [122.1238  ]
 [ 94.84571 ]
 [142.59616 ]
 [138.96619 ]
 [115.81169 ]
 [117.12813 ]
 [144.98465 ]
 [116.46243 ]
 [123.62691 ]
 [152.36145 ]
 [108.553894]
 [147.59314 ]
 [137.09581 ]
 [122.70947 ]
 [142.8308  ]
 [141.1864  ]
 [134.96037 ]
 [113.484505]
 [151.07198 ]] 

100 Cost :  14.840899 
 Prediction: 
[[150.65323]
 [185.09476]
 [180.11232]
 [199.10275]
 [139.62119]
 [107.73281]
 [152.1185 ]
 [117.01439]
 [177.40277]
 [171.04135]
 [144.72797]
 [145.53854]
 [183.19336]
 [148.30978]
 [153.72636]
 [190.23903]
 [138.91275]
 [183.58704]
 [173.5595 ]
 [155.34213]
 [178.00368]
 [176.19354]
 [168.52869]
 [145.13452]
 [189.86458]] 

200 Cost :  14.1101675 
 Prediction: 
[[150.7623 ]
 [185.06221]
 [180.16988]
 [199.101  ]
 [139.60883]
 [107.60502]
 [152.06718]
 [116.9113 ]
 [177.2556 ]
 [170.74788]
 [144.69594]
 [145.41002]
 [183.31598]
 [148.49289]
 [153.64323]
 [190.15968]
 

## Queue Runners

File이 굉장히 커서 memory에 한 번에 올리기도 힘이든 경우에
numpy를 이용하면 memory가 부족하다고 나온다.  
<br>
이런 경우를 대비해서 TensorFlow에서는 **Queue Runner**라는 시스템을 제공한다.  
기본적으로 여러개의 파일을 읽을 수 있다.
<br>
가장 간단하게 load해오는 방법은 numpy에 loadtxt를 이용한다.

In [3]:
import tensorflow as tf
filename_queue = tf.train.string_input_producer(
['data-01-test-score.csv', 'data-02-test-score.csv'], shuffle=False, name='filename_queue')

reader = tf.TextLineReader()
key, value = reader.read(filename_queue)

# decoded result
record_defaults = [[0.], [0.], [0.], [0.]]
xy = tf.decode_csv(value, record_defaults=record_defaults)

# collect batches of csv in
train_x_batch, train_y_batch = \
tf.train.batch([xy[0:-1], xy[-1:]], batch_size=10)

X = tf.placeholder(tf.float32, shape=[None, 3])
Y = tf.placeholder(tf.float32, shape=[None, 1])

W = tf.Variable(tf.random_normal([3, 1]), name='weight')
b = tf.Variable(tf.random_normal([1]), name='bias')

# hypothesis
hypothesis = tf.matmul(X, W) + b

# cost/Los function
# 이 전에 쓰던 것과 동일함
cost = tf.reduce_mean(tf.square(hypothesis - Y))

#Minimize learning_rate를 낮게 줌
optimizer = tf.train.GradientDescentOptimizer(learning_rate=1e-5)
train = optimizer.minimize(cost)


sess = tf.Session()
sess.run(tf.global_variables_initializer())

# Start populating the filename queue
coord = tf.train.Coordinator()
threads = tf.train.start_queue_runners(sess=sess, coord=coord)

for step in range(2001):
    x_batch, y_batch = sess.run([train_x_batch, train_y_batch])
    cost_val, hy_val, _ = sess.run(
    [cost, hypothesis, train],
    feed_dict={X: x_batch, Y: y_batch})
    
    if step % 200 == 0:
        print step, "Cost: ", cost_val, "\nPrediction:\n", hy_val
        

coord.request_stop()
coord.join(threads)
    

Instructions for updating:
Queue-based input pipelines have been replaced by `tf.data`. Use `tf.data.Dataset.from_tensor_slices(string_tensor).shuffle(tf.shape(input_tensor, out_type=tf.int64)[0]).repeat(num_epochs)`. If `shuffle=False`, omit the `.shuffle(...)`.
Instructions for updating:
Queue-based input pipelines have been replaced by `tf.data`. Use `tf.data.Dataset.from_tensor_slices(input_tensor).shuffle(tf.shape(input_tensor, out_type=tf.int64)[0]).repeat(num_epochs)`. If `shuffle=False`, omit the `.shuffle(...)`.
Instructions for updating:
Queue-based input pipelines have been replaced by `tf.data`. Use `tf.data.Dataset.from_tensors(tensor).repeat(num_epochs)`.
Instructions for updating:
To construct input pipelines, use the `tf.data` module.
Instructions for updating:
To construct input pipelines, use the `tf.data` module.
Instructions for updating:
Queue-based input pipelines have been replaced by `tf.data`. Use `tf.data.TextLineDataset`.
Instructions for updating:
Queue-base