# ML Lab08 : Tensor Manipulation

## Simple ID array and slicing

```python

t = np.array([0., 1., 2., 3., 4., 5., 6.])

```

In [1]:
import tensorflow as tf
import numpy as np

t = np.array([0., 1., 2., 3., 4., 5., 6.])


print t.ndim # rank
print t.shape # shape
print t[0], t[1], t[-1]
print t[2:5], t[4:-1]
print t[:2], t[3:]

1
(7,)
0.0 1.0 6.0
[2. 3. 4.] [4. 5.]
[0. 1.] [3. 4. 5. 6.]


## 2D Array

In [2]:
t = np.array([[1., 2., 3.], [4., 5., 6.], [7., 8., 9.,], [10., 11., 12]])

print t.ndim
print t.shape

2
(4, 3)


## Shape, Rank, Axis

In [3]:
t = tf.constant([1,2,3,4])
print tf.shape(t).eval
print tf.rank(t).eval

<bound method Tensor.eval of <tf.Tensor 'Shape:0' shape=(1,) dtype=int32>>
<bound method Tensor.eval of <tf.Tensor 'Rank:0' shape=() dtype=int32>>


In [4]:
t = tf.constant([[1,2],[3,4]])
print tf.shape(t).eval
print tf.rank(t).eval

<bound method Tensor.eval of <tf.Tensor 'Shape_1:0' shape=(2,) dtype=int32>>
<bound method Tensor.eval of <tf.Tensor 'Rank_1:0' shape=() dtype=int32>>


```python
[ #axis = 0 
    [ #axis = 1
        [ #axis = 2
            [1,2,3,4], #axis=3 or axis = -1
            [5,6,7,8],
            [9,10,11,12]
        ],
        [
            [13,14,15,16],
            [17,18,19,20],
            [21,22,23,24]
        ]
    ]
]
```

Rank가 4라는 것은 4개의 축이 있다고 볼 수 있다.

In [5]:
t = tf.constant([[[[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]],
                [[13,14,15,16], [17, 18, 19, 20], [21, 22, 23, 24]]]])

print tf.shape(t).eval
print tf.rank(t).eval

<bound method Tensor.eval of <tf.Tensor 'Shape_2:0' shape=(4,) dtype=int32>>
<bound method Tensor.eval of <tf.Tensor 'Rank_2:0' shape=() dtype=int32>>


## Matmul VS multipy

In [6]:
matrix1 = tf.constant([[1.,2],[3.,4.]])
matrix2 = tf.constant([[1.], [2.]])

print "Metrix 1 shape", matrix1.shape
print "Metrix 2 shape", matrix2.shape

with tf.Session() as sess:
    print tf.matmul(matrix1, matrix2).eval()
    
    # 아래는 broadcast! broadcast는 격이 맞지 않아도 연산이 된다.
    # matrix곱을 할 때 아래와 같이 하면 안된다!!!
    # ㄱ
    print (matrix1*matrix2).eval()

Metrix 1 shape (2, 2)
Metrix 2 shape (2, 1)
[[ 5.]
 [11.]]
[[1. 2.]
 [6. 8.]]


## Reduce mean

In [7]:
with tf.Session() as sess:
    print tf.reduce_mean([1,2], axis=0).eval()

1


In [8]:
with tf.Session() as sess:
    x = [[1., 2.],
        [3., 4.]]
    
    print tf.reduce_mean(x).eval()
    
    print tf.reduce_mean(x, axis=0).eval()
    print tf.reduce_mean(x, axis=1).eval()
    print tf.reduce_mean(x, axis=-1).eval()

2.5
[2. 3.]
[1.5 3.5]
[1.5 3.5]


## Reduce sum

In [9]:
with tf.Session() as sess:
    x = [[1., 2.],
        [3., 4.]]
    
    print tf.reduce_sum(x).eval()
    
    print tf.reduce_sum(x, axis=0).eval()
    print tf.reduce_sum(x, axis=1).eval()
    print tf.reduce_mean(tf.reduce_sum(x, axis=-1)).eval()

10.0
[4. 6.]
[3. 7.]
5.0


## Argmax

In [10]:
x = [[0, 1, 2],
    [2, 1., 0]]

with tf.Session() as sess:
    print tf.argmax(x, axis=0).eval()
    print tf.argmax(x, axis=1).eval()
    print tf.argmax(x, axis=-1).eval()

[1 0 0]
[2 0]
[2 0]


## Resahpe(가장 많이 사용하는 것!! 매우 중요!!!)

In [11]:
t = np.array([[[0, 1, 2],
              [3, 4, 5]],
             [[6, 7, 8],
             [9, 10, 11]]])
print t.shape

with tf.Session() as sess:
    print tf.reshape(t, shape=[-1, 3]).eval() ,"\n"
    print tf.reshape(t, shape=[-1, 1, 3]).eval()

(2, 2, 3)
[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]] 

[[[ 0  1  2]]

 [[ 3  4  5]]

 [[ 6  7  8]]

 [[ 9 10 11]]]


In [12]:
with tf.Session() as sess:
    print tf.squeeze([[0], [1], [2]]).eval(),"\n"
    print tf.expand_dims([0, 1, 2], 1).eval()

[0 1 2] 

[[0]
 [1]
 [2]]


## One hot

In [13]:
with tf.Session() as sess:
    print tf.one_hot([[0], [1], [2], [2], [0]], depth=3).eval(),"\n"
    t = tf.one_hot([[0], [1], [2], [2], [0]], depth=3)
    print tf.reshape(t, shape=[-1,3]).eval()

[[[1. 0. 0.]]

 [[0. 1. 0.]]

 [[0. 0. 1.]]

 [[0. 0. 1.]]

 [[1. 0. 0.]]] 

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]
 [0. 0. 1.]
 [1. 0. 0.]]


## Casting

In [14]:
with tf.Session() as sess:
    print tf.cast([1.8, 2.2, 3.3, 4.9], tf.int32).eval(),"\n"
    print tf.cast([True, False, 1 == 1, 0 == 1], tf.int32).eval()

[1 2 3 4] 

[1 0 1 0]


## Stack

In [15]:
x = [1, 4]
y = [2, 5]
z = [3, 6]

with tf.Session() as sess:
# Pack along first dim.
    print tf.stack([x, y, z]).eval() , "\n"
    print tf.stack([x, y, z], axis=1).eval()

[[1 4]
 [2 5]
 [3 6]] 

[[1 2 3]
 [4 5 6]]


## Ones and Zeros like

In [16]:
x = [[0, 1, 2],
    [2, 1, 0]]

with tf.Session() as sess:
# Pack along first dim.
    print tf.ones_like(x).eval() , "\n"
    print tf.zeros_like(x).eval() , "\n"

[[1 1 1]
 [1 1 1]] 

[[0 0 0]
 [0 0 0]] 



## Zip

In [17]:
for x, y in zip([1, 2, 3], [4, 5, 6]):
    print x, y
    
for x, y, z in zip([1, 2, 3], [4, 5, 6], [7, 8, 9]):
    print x, y, z

1 4
2 5
3 6
1 4 7
2 5 8
3 6 9
