# ML Lab04-1 : Multi-variable Linear regression을 TensorFlow에서 구현하기

## Hypothesis using matrix

variable이 많을 때 Y를 예측하는 모델의 경우

$$H(x_1, x_2, x_3) = x_1w_1 + x_2w_2 + x_3w_3 $$

In [1]:
import tensorflow as tf
import numpy as np

xy = np.loadtxt('data-01-test-score.csv', delimiter=',', dtype=np.float32)

x_data = xy[:, 0:-1]
y_data = xy[:, [-1]]

x1_data = [73., 93., 89., 96., 73.]
x2_data = [80., 88., 91., 98., 66.]
x3_data = [75., 93., 90., 100., 70.]
y_data = [152., 185., 180., 196., 142.]

# placeholdlers
x1 = tf.placeholder(tf.float32)
x2 = tf.placeholder(tf.float32)
x3 = tf.placeholder(tf.float32)

Y = tf.placeholder(tf.float32)

w1 = tf.Variable(tf.random_normal([1]), name='weight1')
w2 = tf.Variable(tf.random_normal([1]), name='weight2')
w3 = tf.Variable(tf.random_normal([1]), name='weight3')
b = tf.Variable(tf.random_normal([1]), name='bias')

hypothesis = x1 * w1 + x2 * w2 + x3 * w3 + b

# cost/Los function
# 이 전에 쓰던 것과 동일함
cost = tf.reduce_mean(tf.square(hypothesis - Y))

#Minimize learning_rate를 낮게 줌
optimizer = tf.train.GradientDescentOptimizer(learning_rate=1e-5)
train = optimizer.minimize(cost)


sess = tf.Session()
sess.run(tf.global_variables_initializer())

for step in range(2001):
    #train을 돌리고 그 때, cost와 hypothes를 같이 기록을 해서 출력을 하는 모델
    cost_val, hy_val, _ = sess.run([cost, hypothesis, train],
                                  feed_dict={x1: x1_data, x2: x2_data, x3: x3_data, Y: y_data})
    if step % 10 == 0:
        print step ,'Cost : ', cost_val,"\n Prediction: \n", hy_val,"\n"
              


0 Cost :  128975.86 
 Prediction: 
[-165.77122 -199.54532 -196.60757 -212.3294  -153.73543] 

10 Cost :  5.889347 
 Prediction: 
[151.91068 182.29681 179.62172 197.37494 137.51692] 

20 Cost :  4.691904 
 Prediction: 
[152.8655  183.45659 180.7582  198.61263 138.4045 ] 

30 Cost :  4.6752076 
 Prediction: 
[152.86201 183.46452 180.75975 198.6144  138.4135 ] 

40 Cost :  4.658601 
 Prediction: 
[152.85564 183.46898 180.75789 198.61244 138.41983] 

50 Cost :  4.6421304 
 Prediction: 
[152.84929 183.47339 180.75601 198.6105  138.42613] 

60 Cost :  4.625682 
 Prediction: 
[152.84294 183.47781 180.75415 198.60855 138.43243] 

70 Cost :  4.609369 
 Prediction: 
[152.83662 183.48221 180.7523  198.60661 138.4387 ] 

80 Cost :  4.5931087 
 Prediction: 
[152.8303  183.48659 180.75044 198.60466 138.44496] 

90 Cost :  4.576936 
 Prediction: 
[152.82404 183.49095 180.7486  198.60272 138.45122] 

100 Cost :  4.5608473 
 Prediction: 
[152.81776 183.49532 180.74675 198.60078 138.45744] 

110 Cost : 

990 Cost :  3.4156709 
 Prediction: 
[152.32513 183.83838 180.6026  198.44366 138.95227] 

1000 Cost :  3.4055305 
 Prediction: 
[152.32027 183.84177 180.6012  198.44205 138.95721] 

1010 Cost :  3.3954613 
 Prediction: 
[152.31541 183.84512 180.59976 198.44043 138.96213] 

1020 Cost :  3.3854241 
 Prediction: 
[152.31058 183.84851 180.59836 198.43884 138.96706] 

1030 Cost :  3.3754401 
 Prediction: 
[152.30579 183.8519  180.59698 198.43727 138.97198] 

1040 Cost :  3.365502 
 Prediction: 
[152.30096 183.85524 180.59557 198.43564 138.97685] 

1050 Cost :  3.3556328 
 Prediction: 
[152.29617 183.85857 180.59418 198.43405 138.98174] 

1060 Cost :  3.345777 
 Prediction: 
[152.2914  183.86192 180.59279 198.43246 138.98662] 

1070 Cost :  3.335997 
 Prediction: 
[152.28664 183.86522 180.5914  198.43086 138.99147] 

1080 Cost :  3.3262374 
 Prediction: 
[152.28189 183.86856 180.59003 198.42929 138.99634] 

1090 Cost :  3.3165653 
 Prediction: 
[152.27716 183.87186 180.58865 198.4277  139.0

1950 Cost :  2.641089 
 Prediction: 
[151.9166  184.12408 180.48459 198.30258 139.37425] 

1960 Cost :  2.6347969 
 Prediction: 
[151.91292 184.12668 180.48354 198.30125 139.37814] 

1970 Cost :  2.628551 
 Prediction: 
[151.90923 184.12924 180.48248 198.2999  139.38199] 

1980 Cost :  2.6223216 
 Prediction: 
[151.90556 184.13182 180.48141 198.29858 139.38586] 

1990 Cost :  2.6161408 
 Prediction: 
[151.90189 184.13437 180.48036 198.29724 139.3897 ] 

2000 Cost :  2.6099582 
 Prediction: 
[151.89825 184.13693 180.47934 198.2959  139.39354] 



<br>
위의 코드의 경우 variable이 너무 많아 복잡해져 스파게티 코드가 될 가능성이 **매우 높다!!**<br>
그래서 다음과 같은 방법으로 설계하고자 한다.  
<br>

## Hypothesis using matrix

<br>

$$\quad
\begin{pmatrix} 
x_1 & x_2 & x_3 
\end{pmatrix}
\quad
\cdot
\quad
\begin{pmatrix} 
w_1 \\
w_2 \\
w_3 \\
\end{pmatrix}
\quad
=
\quad
\begin{pmatrix} 
x_1w_1 + x_2w_2 + x_3w_3
\end{pmatrix}
\quad$$
<br><br>
$$ H(X) = XW $$

In [2]:
import tensorflow as tf

# X_data []하나가 x1, x2 ... 각각은 instance
x_data = [[73., 80., 75.], [93., 88., 93.], [89., 91., 90.], [96., 91., 90.], [73., 66., 70.]]
y_data = [[152.], [185.], [180.], [196.], [142.]]

# placeholdlers
# shape을 주의해줘야한다. 위의 경우 x1, x2, x3 세개이므로 shape 뒤의 값은 3개다.
# shape 앞에 값은 Data의 갯순데 갯수는 추가하기 나름이므로 정해져 있지 않는 경우 None으로 표현한다.
# [x1, x2, x3]가 n개 있을 수 있으므로 [None, 3]

X = tf.placeholder(tf.float32, shape=[None, 3])
Y = tf.placeholder(tf.float32, shape=[None, 1])

W = tf.Variable(tf.random_normal([3, 1]), name='weight')
b = tf.Variable(tf.random_normal([1]), name='bias')

# hypothesis
hypothesis = tf.matmul(X, W) + b

# cost/Los function
# 이 전에 쓰던 것과 동일함
cost = tf.reduce_mean(tf.square(hypothesis - Y))

#Minimize learning_rate를 낮게 줌
optimizer = tf.train.GradientDescentOptimizer(learning_rate=1e-5)
train = optimizer.minimize(cost)


sess = tf.Session()
sess.run(tf.global_variables_initializer())

for step in range(2001):
    #train을 돌리고 그 때, cost와 hypothes를 같이 기록을 해서 출력을 하는 모델
    cost_val, hy_val, _ = sess.run([cost, hypothesis, train],
                                  feed_dict={X: x_data, Y: y_data})
    if step % 10 == 0:
        print step ,'Cost : ', cost_val,"\n Prediction: \n", hy_val,"\n"
              


0 Cost :  62796.6 
 Prediction: 
[[-70.72574 ]
 [-83.77534 ]
 [-83.37135 ]
 [-87.193886]
 [-64.33178 ]] 

10 Cost :  22.859926 
 Prediction: 
[[154.00735]
 [186.4227 ]
 [182.81808]
 [185.98657]
 [141.81094]] 

20 Cost :  21.915562 
 Prediction: 
[[154.85323]
 [187.45088]
 [183.82542]
 [187.03139]
 [142.60017]] 

30 Cost :  21.878506 
 Prediction: 
[[154.84799]
 [187.45573]
 [183.82468]
 [187.04164]
 [142.60869]] 

40 Cost :  21.841646 
 Prediction: 
[[154.83955]
 [187.45671]
 [183.82013]
 [187.04796]
 [142.61424]] 

50 Cost :  21.804914 
 Prediction: 
[[154.83113]
 [187.45766]
 [183.81557]
 [187.05424]
 [142.61977]] 

60 Cost :  21.768324 
 Prediction: 
[[154.8227 ]
 [187.45859]
 [183.81097]
 [187.06049]
 [142.62524]] 

70 Cost :  21.73176 
 Prediction: 
[[154.81432]
 [187.4595 ]
 [183.80643]
 [187.06677]
 [142.63074]] 

80 Cost :  21.695377 
 Prediction: 
[[154.80595]
 [187.46042]
 [183.80188]
 [187.07303]
 [142.6362 ]] 

90 Cost :  21.659178 
 Prediction: 
[[154.7976 ]
 [187.46133]
 

900 Cost :  19.096384 
 Prediction: 
[[154.1959 ]
 [187.50865]
 [183.46365]
 [187.55612]
 [143.0347 ]] 

910 Cost :  19.068737 
 Prediction: 
[[154.18933]
 [187.50894]
 [183.45993]
 [187.56169]
 [143.03902]] 

920 Cost :  19.041203 
 Prediction: 
[[154.18275]
 [187.50922]
 [183.45618]
 [187.56721]
 [143.04327]] 

930 Cost :  19.01376 
 Prediction: 
[[154.1762 ]
 [187.50948]
 [183.45245]
 [187.57274]
 [143.04755]] 

940 Cost :  18.986362 
 Prediction: 
[[154.16965]
 [187.50974]
 [183.44873]
 [187.57826]
 [143.05179]] 

950 Cost :  18.959127 
 Prediction: 
[[154.16315]
 [187.50998]
 [183.44504]
 [187.58377]
 [143.05605]] 

960 Cost :  18.931913 
 Prediction: 
[[154.15665]
 [187.51025]
 [183.44135]
 [187.5893 ]
 [143.0603 ]] 

970 Cost :  18.90481 
 Prediction: 
[[154.15019]
 [187.5105 ]
 [183.43767]
 [187.5948 ]
 [143.06453]] 

980 Cost :  18.877748 
 Prediction: 
[[154.14374]
 [187.51073]
 [183.43398]
 [187.6003 ]
 [143.06873]] 

990 Cost :  18.850801 
 Prediction: 
[[154.1373 ]
 [187.5

1850 Cost :  16.802074 
 Prediction: 
[[153.6475 ]
 [187.50822]
 [183.14333]
 [188.05086]
 [143.39124]] 

1860 Cost :  16.780949 
 Prediction: 
[[153.6425 ]
 [187.50795]
 [183.1403 ]
 [188.05576]
 [143.39449]] 

1870 Cost :  16.759892 
 Prediction: 
[[153.6375 ]
 [187.50768]
 [183.13728]
 [188.06064]
 [143.39772]] 

1880 Cost :  16.738932 
 Prediction: 
[[153.63252]
 [187.5074 ]
 [183.13426]
 [188.0655 ]
 [143.40096]] 

1890 Cost :  16.718027 
 Prediction: 
[[153.62755]
 [187.50713]
 [183.13127]
 [188.07037]
 [143.40417]] 

1900 Cost :  16.697208 
 Prediction: 
[[153.6226 ]
 [187.50685]
 [183.12828]
 [188.07523]
 [143.40738]] 

1910 Cost :  16.676342 
 Prediction: 
[[153.61766]
 [187.50655]
 [183.12529]
 [188.0801 ]
 [143.41058]] 

1920 Cost :  16.655643 
 Prediction: 
[[153.61273]
 [187.50624]
 [183.1223 ]
 [188.08492]
 [143.41377]] 

1930 Cost :  16.634907 
 Prediction: 
[[153.60783]
 [187.50594]
 [183.11932]
 [188.08977]
 [143.41695]] 

1940 Cost :  16.614285 
 Prediction: 
[[153.60